apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: netbox
  namespace: netbox
spec:
  values:
    redis:
      enabled: true
      master:
        persistence:
          size: 1Gi
      replica:
        persistence:
          size: 1Gi
    tasksRedis:
      host: netbox-redis-master
    cachingRedis:
      host: netbox-redis-master

    resources:
      requests:
        cpu: 100m
        memory: 512Mi
      limits:
        cpu: 1000m
        memory: 1Gi

    housekeeping:
      resources:
        requests:
          cpu: 50m
          memory: 256Mi
        limits:
          cpu: 500m
          memory: 512Mi

    worker:
      resources:
        requests:
          cpu: 50m
          memory: 256Mi
        limits:
          cpu: 500m
          memory: 512Mi
