---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: operator-oauth
  namespace: tailscale
spec:
  encryptedData:
    client_id: AgAvUq7orR9OrdxhYqsE76JXuQwHTPHBmcu0RuQ3dMFe0Dlt9bhHB/rIucGizrO+KQerKDBYPQTpISJsbh6vGCcT43AV24wsz7lBHKrVegdyhqzIgUC8xkgXnMlUnXeGr5oVE3CBiPiLuBrMEvz7FHVsz6lh81cMJGPx43oHl5MSndJwghPiw5FA25W4JUWCf2qrN1O+3rsCrHGyb7GFdaainmbXI4vgEZI2n1GI0IEGpKnaMT2AQoOUi6Ekyb0ULEfTibUZKEgUGFaJFeSpl7yoXAOpWGnhDHksBe7EQ97RMAw/3JiMuYtAoD3L7jA3qLVWNaNh7K3fPlOusrz/XtT8kwpXtvPfbvT2YrwZS4ekyIqa25ecKbDn4XioWffMbMWgLCqk5J5bRvFAwXNe77XmICSeozDLX2Xhx7PH0AleMSLeBVmbpN6IDxvVq9kzU9ABNDDPeqcSejJJRUJvgYHrpy7dbgO6qHEt/5+NZPOA619i/E5uL1Jrd1fCGTijgYtUlER23RG01Wl4gtPfJ2C5i6WcpUu0A+cJEnoJCmqIHDAFwda48iLh58FO3giQMQvhdF/GvBmIQfB13UHDtD3VDDinVZiHZSO/eL5DSrpeSkdv65lLUCzKKqdtdGbutcEtPOajjD9V6k0iUCgKIObcgDWzCVvDlj0STu+RC8hdwMm5MQNlL0YtZGRxa+1BBNiguZurxCScHyVio6WNtcxO2w==
    client_secret: AgAfBtBBAt6dCgd/Cqly/8P01wjwy0nBXTWdaDkqDd0j+X7ZnnDAga1PgL2G2grZUUSANgOkCvlzm6O4FmtigfZz5ZdUaZKZZ1jVeavnil3FDDESL8oC3EZkI0LTwoaTH5CQxbn6UUt07tAm3Bv1s/vgefAFZojmMHzgBGq49ZzUCGlrPnTA3hcRjALxCbxrfMXT0XKRUziFNXCIJN3c3N8IfeOidADQ3gfHLMEfSix0Ndf0iXXn5jCUXR+6ORMpgbXSjYSL6P1nlKXCKi7JCTOZnLDVYndWMVTEWJa2LOr2stuD+t1noTtygc4HChIzMmw+m2mP76ALKmNoJ2D5JnglW/PmHIiUh7aPRsdsdTZLWT/zu4BIkN67iZ9L460I+bImSKj8dbltrqLhwAQGHP2IUXNcr/DCZojFhCyCkaHaLy+EclL7IlSzashcAQSMUDSfRdkghVHVrgII33+73rJPhharahyNt+gcLkVnvOspyYgAD06tusv8pO+lPNleBn+WD6TEiPqmKa6nni1gVaiIoU3XuPKN1EOQ08vLceshWS+pVLH+BRyD6dOHRf5srb/fu6fXJEedJtvmcx5cVHcqVjgLWISXwOVRFDPJBZAFCdtmhA/Tqi4oCCEWJpHWpgcwx2IhSgPdr2fWc7L8UB6/ZHledf7k3gcy/pViMXCPAiq5R6GRmb63w1pymBXYvSWlM/8E6pK3B05XY6H6ZcR8BkhZSZhVtX9zPZKs0S1T0QZLtPrdoYPqp4+OaNel1G+E+qnqXSwZDQE2ZxuJKgXZ
  template:
    metadata:
      name: operator-oauth
      namespace: tailscale
