---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: operator-oauth
  namespace: tailscale
spec:
  encryptedData:
    client_id: AgC6uIb+Xq0DCSzQiaD/ihXojlcVwJ0u+lWozE3lQdxCwmqWc0zirCt9ywfCbQVxoDuvYZ1gOji1+LxmBLW4JeXqcP/TXnqTTR93mxcISOzbC+XBHyZULCI9rVWDVWdWuFB14cL1qgHtIBg9MoIv4Ez7GRMjIZD2dMft1SH+VcdqnsyW98IybYAM9nPuydgLOA96VYVXdYSY43olayRP8ld+9abJjdDAH27A7Vo+CE0lK8+n/uW33hyYs3/63FDwTxkk0Zt6bTjsaHiBgQZXHLfbjsUMHAg2HBiZ4NhRcKSMWPUDYl2FiY+l7nGgB9gs4/zKdpfprNRVTaC8WMJMomqt2tFzGl/Bj74sBwm6sUBSxg9KG5fXDIwH7aNqE2JlMFTLPWz4dVk9k75mW9eiKzFwnTRHV11JeSIg7wggXOG9WgXIgPsLEd7vlta7GJzNEqI8R0l7yWv+mS+qW6Hm7XQOHgH+dSLwlGReGKLDyh2x2RF2AN5nj/20uvDjo3ccvdsXl2kYKZoHeIV6mb5ePcb/IGtTj2HkdXCquJLVKKZzb8cz3kOV0AdS+gV63Q9ZP/fVIRsHL3NaIF9LzZZHsuXp1lsoqKgKBPU5YeKNoTzL18/UNM6g5QDFNKAWhFEeqA/a2QQx1sQiKKsRQ3hsJR69ONtEYupu5llo29wvWtWdO6vX0bytkaN8NedJiH3J2U49t+/a+dJj+VVdAxMFN6cB4A==
    client_secret: AgARds/4q05pp4t1qRIuEKZaD0rI4vRa8LH+ZvC1MLJhJDh9BJlIJF2Jj2xBru6/wp2QdiFTCNloOqkkdyiytyjo+u2U5WGbGRDVG5xu2y/LPl7+LtwVidZPbTXgGrbsMU0QmGxslrnQHBFJsCTgCnDW5eTn/eeXREKxYehsjlYt+ogxdwbBwtqvW7xKEJ76qB6lDdAacDtrpc2Vur3B0Hc7pZzXfB8eXHA5YEuhr5lpxGYRnpdXMBUwyLnuHxGCUNCA3Aca4B0Lks2syd0CuNaHlswxmaU1D79inWJI9iCNjuto5SBj+/enlwqT6ZwPZFel75PU5MR1dwV+R0OTedmosfoiIhvcB6yzOcmPnQicqrTo2B5DGyp7LT+8H8csKqH3/GptMtWKIE9ccllHCaYMpOy8BeMkNX/e0sKo1CY+ZQsau8gGfrsqS6gtPYNAmvEVtErNYhtDoGo3fagkT1yADSZaSxh4BNi6WcOe9tom4T7P/CyW59yYxc68EceaFEUz6xZaDXK4VWFq8ScCI9OEWSNjuhx0MXijB9Xyot+5Gc/NQE+7Tv7BWJfq7pZdQPspJ/JrliFD3Ec4V5VeJnncWt/ciMWRjFkBTApxoIRbpo08EIa4KlU9ChLGVfCU5USzd0vUMjx7Dy2dDG0ru0X3IzX6+9oTC9PTOQbXLFrddj8tsZxrpuO4/syCoqQXOtUvD0gfV/SNy+uS5bCXHxhqKi8BBBerVFyDgceGM1HbgBVaBS31MJkMXsvLToME1ChbYyurCQ7ITASWFmMUxmPJ
  template:
    metadata:
      name: operator-oauth
      namespace: tailscale
