---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: vaultwarden-admin-token
  namespace: vaultwarden
spec:
  encryptedData:
    admin-token: AgB9fUnFeMgpLzWSQxBv/VgFTaWgNONkuyd0o6gkxrUU6JDJE46D8LzX6atActRqlrkdw0IXYXGKXn/6Erj4QgsjwDoMYCKFoDCPmpVkhNy3TbE6pkoK8iGZ7Ze8501U1U74Qm8hMEqboj+qDMuvWDLNablFC/bQpcWQ9Vkc8a16X256bI3I1bUngfBLmBBdBExNN563OAO2Xm34I9970CT7+KWjLaEa4lkHk6b+X9hU5wt3MXo6eIbdQjRmdABe69pPhvUQcRsk7sDNl2koLfoz1n0/OwZXpEcO5YUI5VxI6O/XTp9LQK56M+8iWNmbqcJjyNTPb+sh9nzQUGHDsKnbyHOQ+z1veajWAbfnYm9BUOQuUdKtDI6WBmSWD41Z0MP7hsI0HyzBMrXj54PnjyrUNujOu6w8cqvgeBsS2vm+H78CsS7SA/89t9hejcmY2Dz8vWlRFomE3wivgmggz2nS6Gkcw1JXiOuU3Y5/pM88Cci8Z3TEi+lgD/X0IDXGmvnXu5mIHDjxLZ54Id+ahi1ULxRIpPjeux5H4lIBG13Zzm2dnw8zCP+xT+2xnis5szNYM0B5IE634GSIgI2RJ88z2njXLr+g7xZ1M1Vak/fldQarpZnPIA31DyYyyWv+eqZtC/U0UvKh4wpAViWzgp7cLxcnWVS65Uq2TJ5YK84bjkNSp01afr4P/sJx+qTsxpJVkZ/TomcEGflynq2pqTw9yokxwiTIrclIMqFQMFSgnpO9aoNfrlu0lL92oeEeotwqSd31VZ1CzsuutibWbBwOjbrIKK1n2WEcXkMpSG7IPnzI59pkY2i8CR+Yk8IP11qj4P8H1WPUFi3nAspVDdKXKqUu1VPedpblDao6+7Muu0ooVACM9A==
  template:
    metadata:
      name: vaultwarden-admin-token
      namespace: vaultwarden
