---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: vaultwarden-admin-token
  namespace: vaultwarden
spec:
  encryptedData:
    admin-token: AgBM4PQh1rmbjrKfDUYc6L4f2YFS78WQ9csalgAhOSik0OFUfsfysUO3V2HfmyOSP8VPW9i0CjeLzPqBF9b+vtEinsCEVlrdaPzuzItNF9yTZxoKKxr5hMcjEzgRQvGMKanb5ATaoNvhZlMOzsLo3Rmei++N0dW0/BsVE2NdXg0GyHLT+hhYvFzoNHgAxR1cR4QNmCLlAZVgqv+rEPLh8TzKqzrOJbknuOixU6eo4t52QvYqvmxsD6FtfIw7XG98fPpqXU5O/FUQQw/kx2polWrZiIkg/8H8LrqhQHBAdoznRho3De6SeF/e0dlZCcXNFhFn5TkZS2yTfRlJANfO5nIXDhs9/n6D75qC/0QXsnKACvuHaNTYZ8Rfqb95qGX6b2Ta7Q8oVZ1mQQ6l7efda8VySgZ6gerJVzI1cBc8Cgd8vhGxtN8u1TOIHaSBhQjXMlS64yol/as4hLv+Miue0dSKwIdgxbFDPPr9v1dckLkHNOdGYrZ4COkNkv2NNzI1Ns1FOi5D4FA003glvWBIEVUJuq6aL2vRrCb2VoThecUBFOgQ8j3+uTCrCuIvwQS7XvVcZJOFE+zL/kOqB4451rlZLIEnoyEhhFCXlrMWgUJmvYFSnNWsVVS3EtWJOMud5PEewB4YsZxbkustVMO+RBM9rjKqCSlk29kTCFtKWfp0j8VKnJk/M1Hsnm44JFo6ls84RawB8gIu2XLxhePhHuQnnUR1zjdzqhLX8qHzZhISLDbSPOgRt/i6BSZNSVWLvFK2hak2yuPTsfanWhRfqWqVTpIvYzdT5+7sJdXjZ2xdVcNtpREpJA9Pr+xtrYQimqxlIGWnk+1cCCbqStHbC2VwE56YDYKq
  template:
    metadata:
      name: vaultwarden-admin-token
      namespace: vaultwarden
