---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: vaultwarden-admin-token
  namespace: vaultwarden
spec:
  encryptedData:
    admin-token: AgDlsYq3GeWX+vknWUrrpNqzDDaZLld5td+707cRxebviS7l3PhDbfANzNWk3xMKOaXcW8vP+xL8ZWqHhDiq02bveksdXygqRGSm/WU82atQfz3L3veS0kR+xad0tqSKScpzmWGevw5as+FFYhJYrIsADyMDAqZXulawk3fYzo5cYyVy+dpW2+nH5Luymmm93LfEcGA1PSJQYyWuT9punie+3ActXGwk8SwonzbEn1onCUbn9rdm/2Sv8yQCG0VW7k0zJZ5etg25SSSYc7IJ7cW//25IhRbCZ4BVUcoxWHd4Ttz4zf2LV2fs3NeNfEPLw1p1I4jj1I7ahWuLELgRqxy37cKQPWswDwcvoSDf9fPWtoS3BFuVwpp0YINEOQdlVnVT5kmtHLloDxoC4xR2GyRCCQJrAngs2wiCMvLIrg02r4Pb2Y079lN4UbYYjEV/O3yO4edkHeNVolVCj3c8sKTQ1j2C8T6rmpdUFyVc/WCtZ2V6X2MgfgLXoIQyAB85t5MDpKFux5z0vCJVcs8XSh9y1CgNWb+B7XrFtMD7cQzJFyEz4+jwXa4yDji4Q6RFbCvKhEEE15dDqVXAqpV3Ocg5XShEupTGD5KRzJ17ex3P/GVNseC7gu1DcHFmxegmw55qllonEItFY6QSm29ZUHVFxtIGWZIP4T+Ple6StCpRha7Xk/6yKc8lKpHFCQqujeCkpAUqdRe9lQ/MPFjuHQJLW9VPzVjoz1vMzZhbGfrhjkeriSis5vLVPrdHMSEL8FVAWINuCpcGAQQh7vxFiADR
  template:
    metadata:
      name: vaultwarden-admin-token
      namespace: vaultwarden
