apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: tailscale-operator
  namespace: tailscale
spec:
  interval: 30m
  chart:
    spec:
      chart: tailscale-operator
      version: "1.92.4"
      sourceRef:
        kind: HelmRepository
        name: tailscale
      interval: 12h
  values:
    oauth:
      clientId: "" # Loaded from secret
      clientSecret: "" # Loaded from secret
  valuesFrom:
    - kind: Secret
      name: tailscale-operator-oauth
      valuesKey: client_id
      targetPath: oauth.clientId
    - kind: Secret
      name: tailscale-operator-oauth
      valuesKey: client_secret
      targetPath: oauth.clientSecret
