apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: tailscale-operator
  namespace: tailscale
spec:
  interval: 30m
  install:
    timeout: 10m
  upgrade:
    timeout: 10m
  chart:
    spec:
      chart: tailscale-operator
      version: "1.92.4"
      sourceRef:
        kind: HelmRepository
        name: tailscale
      interval: 12h
  values:
    operatorConfig:
      hostname: k8s-staging-operator
