---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: operator-oauth
  namespace: tailscale
spec:
  encryptedData:
    client_id: AgC+uXd49LItV2DvgcLmcon+Ko1XKpo3jcUTbMc960eiT3XfEo/yzHUVDnuaN0tmMk2w9aVujMdGinCMfc3tjUEiE6TTE26XpMDwUoTsR5yG4so7TBx0mD2GfTD4slh0TYyZhPwB2szYMZkAxhkFr0MfvcJUQn7XsTvN1whpNWdwajoVcus4y8R29CiiN93aP0aD+vjJTBFyG4JGbM9Ufl0dV/PSytNGsftn1fMo2v+IwxVb8jItPKCyTWTkgGvNeYh9AakEkWle4TTFjmN8V6aI661hIcDt7rvKgDUnJ1O1pgawtszmB+irpttD20j92zQ/QQUzqLSItX/N+/a980PmM3N/6WTqn1OQRBtUjoQ+iLXiquZUCMC7S31uMAKQrT6xrpoyt+bUlrw3ZliGqH9rGknlgE4Nn955Mj4G6Eug+r5bEwnmhHyAySyDsyEfgwiIEPS8gQSSh6wOGH8Yi2QPZs+lIGxQpI5kj4KzAwkdoJVQuBCcJILddDxP3k/8rDVKdRm/+MkeNh79Y5z0uCaCOEKXcbgjNOtojpeLw1dxA37tRCzDbo0JUMlKMu8HGtA0je644tEIY257PQ5dQ51+zr9mvypeZsSAAuBHxmfpBc82Au5bx27CXFreMlibPumVv1JEz1/VFmsUAkt7YP8YgCZlWVXkolyr2X4M1ENJefmeqGvQucv8EXF+PRbLHVkYKadNACLd3NeKrQLnoDArxw==
    client_secret: AgBnL9PYHYnnJDTGcpqO4qFQ6WvCCqQN0nNXmqhmVyHeSwBveh+S6KEPORubpHvebzLm913TiT3Z6I4R/nfPMRcl7EFh+jFwE1nK06PNUVX0/daTUr6fECKcgWEOngpc2yCDKuoTRGa13JDZEMvFOoMY6M7ZLXO9zh4Rio3qObTRmlcX1ZVGevm1Zla94XKBDiQEaMR+Ac7YBLtYZHIctpTID1F9sQ3oF7Lb/yY2zB5ceXvtabggPf7MAN/lanhjoP+m1Df52eAFy9BQkfET7VKkiAjz68PjTlsuwpFdXizLABDcVBb1EVfsJ//bj7JXRP2oOFI2T0uyJXLhHE7DmKa6BVFi03exAqDJ075XbRmVUcy14MBI58bEOB5qsDmBegJJh3zD8koWPyBZOF+Yb6BhWHV0d9ca28iMODiHZPqrwCrz2nUBg8mNFKvVT8hl83YVR1u9eHJV08xdpH6boadSrt97IhpZd39vAwRRkQyuLcsTTaM0avQo1P51F06t2mOX56k8AfJCLF56sZefwvDgMfLUJHcKCFMKtvxm8/p1z6qMHcDVrvRBe63/h+HQtfTOITQDmXHbpe/iMPBJksFyXiM2WM9nCyOtN1nEMuFADL0fkHcpqtYdUEUq9bWAb4Q8WUbtNkklMP2AlbC6zd5Ex0KQk1nLRZg353iwxgCWNfOcu+yGPnwNKUrGaFMv36Roe1K8P710bAVkTtZLm9zWYMgIZTUxR3smFejHBZuyx5XmzV/FeJNO3uhWcipbyQsyqCTeVH7zLpr5XcSzmCJC
  template:
    metadata:
      name: tailscale-operator-oauth
      namespace: tailscale
    type: Opaque
