---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: operator-oauth
  namespace: tailscale
spec:
  encryptedData:
    client_id: AgADZVxRm/EBqI8qgNNbdp9iZuukF/0GGd0wZHNFBYfNTYtdJYHW534VWZH7PefZEzgaSYFTWd+e/IEw9ZqUnadZ2YTx9Q9QW8xxNyHw2xOJjVQ8dDIPWNyu2sxKOElShNkjDMnlwk3oqcopj9VM9O0gLygltIQzdy+q1x6S34Egc5lUmgZVqkvNpV/OyvWf6tOkO+66At/kaSV72ILqkNMwNSKdP3xz7mIyT6/4f0pZKW0LdmGKtHsHuRNnKVcnVcWFxsDgPEry9uwbUZvHuM2CMEcUoksQ4yD8Bq28HM5h7v46RY6tdMI8Pr49Da+GFSA4glGt8j1HSTSX7JzRjfJqHow/YIq3es7eyHPGdMCZFSuJ6vTyEJmu0lZ+zcT1I6bVzdy4dCUA3KpSjQTZpGKXhfZGgC4Nc1sIOSIiKT8YHRgsAga1MB4tS1xKQ4PWKN8ebm9Eg6LjgEwc76U0eTRxceNCVyd/0kzlERFdVM+XkJYPUo82T3DYQSbqreyPbgHPf9XCPcJsUSA67Aj4pt4HRaghbAV3QjeDatne1SK55X2w0ivDO+/PsSvK9efwv6UKs+two6J9CNY2j1A4S0UuUUUqYaEVwgbUnXaYkv5NMoqji9E+cTXQlm+7PQdC6jm5GFYTzCk8TAVJbGjdTonAd40HNHFvx18qXJirilRcMNHRlRQjzGmeGSE26NUf9eM4ouoVF4iqjFV+HJC7EOgYMA==
    client_secret: AgBABqrJkuBQOaipuFFS0qEzhv37C95UCKqfNwxMbi99RL+fdxs+ZfbxAdmRTyYImfsVyXTt6qEhBZsal6g8Sqq189rNRwwIOyCQCsNJSPCq2+ZcTwDP3gV+N7W176ZIVui7NR8i8JZcJ/QlvaL+f9HcF8zMbd3MgeX8zmLokq4kHvENLpkqK2lz/1FkEJOBTTaGX37Oq0OBxA8fHzUROFrlPQ3EhER61sLXgyuQ/hyuh8Cl2ydZnrpDU4qWXydCBmGAxF/+gO726b1sNyMVsHBrLugzvekEMfMOox91ulxLTN3KPATc7wcKLevB4x5Y9/i6uPF+pyVgfZLp0woq3COkhNiPf+EhrrPTfV8K3WVSz9s3Cew4Xr48LJpCl/lbj327Mf6Qv6qKWBa0Y1wJ/gDNZNhKeP/4b7cOaNbgSHfOLLhw1y7J8AhKkCDfS9QTq9Q4mWJEOW4zVZ7SjsNvnqhUHdJpj48pnM4ZReXrYokVURCN4I5s07mIlEi0G2VCwAzFyKgqzfZrjgbh4d3g4qlxyhe6v+VaRNWTfppLQNbUdrWjZd31QMTb7ap0097rtry6iB0tR+Qf0sSI52kSMYpnlpqoKo633e5ykF9KGoFeqiuNheWSU061cdLyjNttLTSE92t7DyS1i3IwaCCmNakaiSlN0GYidWN8JrGFIW6DnUf5NTUXZ2y7tCKN3vgBBeqYYbY7U+G10Fr738ZbUvNZQ26sCU6DqxDqvPJcfJGXSWnpzlEBwlkJwtjiFs0m5vpZp0Ql6Uy7mYeq/9cimlr2
  template:
    metadata:
      name: operator-oauth
      namespace: tailscale
    type: Opaque
