# Create this secret in your overlay using SealedSecrets

apiVersion: v1
kind: Secret
metadata:
  name: grafana-admin-credentials
  namespace: monitoring
type: Opaque
stringData:
  admin-user: admin
  admin-password: <CHANGE_ME>
