apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: loki
  namespace: loki
spec:
  interval: 30m
  chart:
    spec:
      chart: loki-stack
      version: ">=2.10.0"
      sourceRef:
        kind: HelmRepository
        name: grafana
      interval: 12h
  install:
    timeout: 10m
  upgrade:
    timeout: 10m
  values:
    loki:
      enabled: true
      persistence:
        enabled: true
        size: 10Gi
      config:
        table_manager:
          retention_deletes_enabled: true
          retention_period: 168h # 7 days

    promtail:
      enabled: true
      config:
        clients:
          - url: http://loki:3100/loki/api/v1/push

    grafana:
      enabled: false # We already have Grafana

    # Expose Loki for Grafana to connect
    service:
      type: ClusterIP
      port: 3100
