apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: loki
  namespace: loki
spec:
  interval: 30m
  chart:
    spec:
      chart: loki
      version: "6.49.0"
      sourceRef:
        kind: HelmRepository
        name: grafana
      interval: 12h
  install:
    timeout: 10m
  upgrade:
    timeout: 10m
  values:
    loki:
      auth_enabled: false
      commonConfig:
        replication_factor: 1
      schemaConfig:
        configs:
          - from: "2024-04-01"
            store: tsdb
            object_store: filesystem
            schema: v13
            index:
              prefix: loki_index_
              period: 24h
      storage:
        type: "filesystem"
        filesystem:
          chunks_directory: /var/loki/chunks
          rules_directory: /var/loki/rules
      limits_config:
        retention_period: 168h
      compactor:
        retention_enabled: true
        delete_request_store: filesystem

    deploymentMode: SingleBinary

    singleBinary:
      replicas: 1
      persistence:
        enabled: true
        size: 10Gi
      resources:
        limits:
          cpu: 1000m
          memory: 1Gi
        requests:
          cpu: 100m
          memory: 128Mi

    gateway:
      enabled: true
      service:
        type: ClusterIP
        port: 80

    # Disable components not needed in SingleBinary mode
    backend:
      replicas: 0
    read:
      replicas: 0
    write:
      replicas: 0
