apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: wikijs-ingress
  namespace: wikijs
  annotations:
    cert-manager.io/cluster-issuer: staging-ca-issuer
spec:
  ingressClassName: traefik
  tls:
    - hosts:
        - wiki.staging.local
      secretName: wikijs-tls
  rules:
    - host: wiki.staging.local
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: wikijs
                port:
                  number: 3000
