apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: vikunja-db
  namespace: vikunja
spec:
  instances: 2
  storage:
    size: 5Gi
  bootstrap:
    initdb:
      database: vikunja
      owner: vikunja
