apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: netbox
  namespace: netbox
spec:
  interval: 30m
  chart:
    spec:
      chart: netbox
      version: "7.2.26"
      sourceRef:
        kind: HelmRepository
        name: netbox-community
      interval: 12h
  install:
    timeout: 10m
  upgrade:
    timeout: 10m
  values:
    postgresql:
      enabled: false
    externalDatabase:
      host: netbox-db-rw
      port: 5432
      database: netbox
      username: netbox
      existingSecretName: netbox-db-app
      existingSecretKey: password

    # Only secret_key is required - superuser configured via web UI after startup
    existingSecret: netbox-secrets
