apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: netbox
  namespace: netbox
spec:
  interval: 30m
  chart:
    spec:
      chart: netbox
      version: "7.7.24"
      sourceRef:
        kind: HelmRepository
        name: netbox-chart
      interval: 12h
  values:
