apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: netbox-db
  namespace: netbox
spec:
  instances: 1
  storage:
    size: 2Gi
  bootstrap:
    initdb:
      database: netbox
      owner: netbox
