apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: vikunja-db
  namespace: vikunja
spec:
  instances: 1
  storage:
    size: 1Gi
  bootstrap:
    initdb:
      database: vikunja
      owner: vikunja
