apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - helmrepository.yaml
  - helmrelease.yaml
  - grafana-sealed-secret.yaml
  - alertmanager-discord-sealed-secret.yaml
configMapGenerator:
  - name: grafana-dashboard-traefik-17346
    files:
      - dashboards/traefik.json
    options:
      labels:
        grafana_dashboard: "1"
      annotations:
        grafana.com/dashboard-id: "17346"
        grafana.com/dashboard-url: "https://grafana.com/grafana/dashboards/17346"
  - name: grafana-dashboard-cnpg-20417
    files:
      - dashboards/cnpg.json
    options:
      labels:
        grafana_dashboard: "1"
      annotations:
        grafana.com/dashboard-id: "20417"
        grafana.com/dashboard-url: "https://grafana.com/grafana/dashboards/20417"
