apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: cloudnative-pg
  namespace: cnpg-system
spec:
  interval: 30m
  chart:
    spec:
      chart: cloudnative-pg
      version: ">=0.22.0"
      sourceRef:
        kind: HelmRepository
        name: cloudnative-pg
      interval: 12h
  install:
    crds: Create
    timeout: 10m
  upgrade:
    crds: CreateReplace
    timeout: 10m
