apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: longhorn
  namespace: longhorn-system
spec:
  interval: 30m
  chart:
    spec:
      chart: longhorn
      version: ">=1.7.0"
      sourceRef:
        kind: HelmRepository
        name: longhorn
      interval: 12h
  install:
    crds: Create
    timeout: 10m
  upgrade:
    crds: CreateReplace
    timeout: 10m
  values:
    defaultSettings:
      defaultReplicaCount: 3
      defaultDataPath: /var/lib/longhorn
      # Allow control plane if needed
      taintToleration: "node-role.kubernetes.io/control-plane:NoSchedule"  
    ingress:
      enabled: true
      ingressClassName: traefik
      host: longhorn.localhost
