---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: vaultwarden
  namespace: flux-system
spec:
  suspend: false
  interval: 5m
  path: ./apps/vaultwarden
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: wikijs
  namespace: flux-system
spec:
  suspend: false
  interval: 5m
  dependsOn:
    - name: cloudnative-pg
  path: ./apps/wikijs
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: vikunja
  namespace: flux-system
spec:
  suspend: false
  interval: 5m
  dependsOn:
    - name: cloudnative-pg
  path: ./apps/vikunja
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: homepage-wordpress
  namespace: flux-system
spec:
  suspend: false
  interval: 5m
  dependsOn:
    - name: sealed-secrets
  path: ./apps/homepage-wordpress
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: stirling-pdf
  namespace: flux-system
spec:
  suspend: false
  interval: 5m
  path: ./apps/stirling-pdf
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: netbox
  namespace: flux-system
spec:
  interval: 5m
  dependsOn:
    - name: cloudnative-pg
    - name: sealed-secrets
  path: ./apps/netbox
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
