apiVersion: cilium.io/v1alpha1
kind: TracingPolicy
metadata:
  name: privileges-raise
  annotations:
    description: Detects privileges raising operations
spec:
  kprobes:
  - call: security_capset
    syscall: false
    message: Process changed its capabilities using capset system call
    args:
    - index: 0
      type: nop
    - index: 1
      type: cred
    - index: 2
      type: cap_effective
    - index: 3
      type: cap_inheritable
    - index: 4
      type: cap_permitted
    selectors:
    - matchArgs:
      - index: 2
        operator: NotEqual
        values:
        - '0'
      matchActions:
      - action: Post
        rateLimit: 1m
    - matchArgs:
      - index: 3
        operator: NotEqual
        values:
        - '0'
      matchActions:
      - action: Post
        rateLimit: 1m
    - matchArgs:
      - index: 4
        operator: NotEqual
        values:
        - '0'
      matchActions:
      - action: Post
        rateLimit: 1m
  - call: create_user_ns
    syscall: false
    message: Unprivileged process created a user namespace where it will be privileged
    args:
    - index: 0
      type: nop
    selectors:
    - matchCapabilities:
      - type: Effective
        operator: NotIn
        values:
        - CAP_SYS_ADMIN
  - call: __sys_setuid
    message: Privileged operation setuid to root
    syscall: false
    args:
    - index: 0
      type: int
    selectors:
    - matchArgs:
      - index: 0
        operator: Equal
        values:
        - '0'
      matchActions:
      - action: Post
        rateLimit: 1m
  - call: __sys_setgid
    message: Privileged operation setgid to root
    syscall: false
    args:
    - index: 0
      type: int
    selectors:
    - matchArgs:
      - index: 0
        operator: Equal
        values:
        - '0'
      matchActions:
      - action: Post
        rateLimit: 1m
  - call: __sys_setreuid
    message: Privileged operation setuid to root
    syscall: false
    args:
    - index: 0
      type: int
    - index: 1
      type: int
    selectors:
    - matchArgs:
      - index: 0
        operator: Equal
        values:
        - '0'
      matchActions:
      - action: Post
        rateLimit: 1m
    - matchArgs:
      - index: 1
        operator: Equal
        values:
        - '0'
      matchActions:
      - action: Post
        rateLimit: 1m
  - call: __sys_setregid
    message: Privileged operation setgid to root
    syscall: false
    args:
    - index: 0
      type: int
    - index: 1
      type: int
    selectors:
    - matchArgs:
      - index: 0
        operator: Equal
        values:
        - '0'
      matchActions:
      - action: Post
        rateLimit: 1m
    - matchArgs:
      - index: 1
        operator: Equal
        values:
        - '0'
      matchActions:
      - action: Post
        rateLimit: 1m
  - call: __sys_setresuid
    message: Privileged operation setuid to root
    syscall: false
    args:
    - index: 0
      type: int
    - index: 1
      type: int
    - index: 2
      type: int
    selectors:
    - matchArgs:
      - index: 1
        operator: Equal
        values:
        - '0'
      matchActions:
      - action: Post
        rateLimit: 1m
    - matchArgs:
      - index: 2
        operator: Equal
        values:
        - '0'
      matchActions:
      - action: Post
        rateLimit: 1m
  - call: __sys_setresgid
    message: Privileged operation setgid to root
    syscall: false
    args:
    - index: 0
      type: int
    - index: 1
      type: int
    - index: 2
      type: int
    selectors:
    - matchArgs:
      - index: 1
        operator: Equal
        values:
        - '0'
      matchActions:
      - action: Post
        rateLimit: 1m
    - matchArgs:
      - index: 2
        operator: Equal
        values:
        - '0'
      matchActions:
      - action: Post
        rateLimit: 1m
  - call: __sys_setfsuid
    message: Privileged operation setuid to root
    syscall: false
    args:
    - index: 0
      type: int
    selectors:
    - matchArgs:
      - index: 0
        operator: Equal
        values:
        - '0'
      matchActions:
      - action: Post
        rateLimit: 1m
  - call: __sys_setfsgid
    message: Privileged operation setgid to root
    syscall: false
    args:
    - index: 0
      type: int
    selectors:
    - matchArgs:
      - index: 0
        operator: Equal
        values:
        - '0'
      matchActions:
      - action: Post
        rateLimit: 1m
