apiVersion: cilium.io/v2
kind: CiliumNetworkPolicy
metadata:
  name: vikunja-ingress
  namespace: vikunja
spec:
  endpointSelector:
    matchLabels:
      app: vikunja
  ingress:
    - fromEndpoints:
        - matchLabels:
            k8s:io.kubernetes.pod.namespace: traefik
            k8s:app.kubernetes.io/name: traefik
      toPorts:
        - ports:
            - port: "3456"
              protocol: TCP
