apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: cryptpad
  namespace: cryptpad
spec:
  interval: 15m
  timeout: 10m

  chart:
    spec:
      chart: cryptpad
      version: "0.0.20"
      sourceRef:
        kind: HelmRepository
        name: cryptpad
        namespace: cryptpad
      interval: 12h

  install:
    remediation:
      retries: 3

  upgrade:
    remediation:
      retries: 3

  values:
    image:
      pullPolicy: IfNotPresent
      repository: cryptpad/cryptpad
      tag: "version-2025.9.0"
    replicaCount: 1

    persistence:
      enabled: true
      storageClass: ""
      size: 10Gi
      accessMode: ReadWriteOnce

    # Ingress configuration (REQUIRED)
    ingress:
      enabled: true
      className: traefik
      #annotations:
      #cert-manager.io/cluster-issuer: letsencrypt-prod # If using cert-manager
      hosts:
        - host: cryptpad.localhost
          paths:
            - path: /
              pathType: Prefix
      #tls:
      #  - secretName: cryptpad-tls
      #    hosts:
      #      - cryptpad.example.com

    # CryptPad configuration (REQUIRED)
    config:
      # The main domain where CryptPad is accessed
      httpUnsafeOrigin: https://cryptpad.localhost

      # Admin email for notifications
      adminEmail: admin@example.com

      # Optional: Sandbox domain for security isolation
      # httpSafeOrigin: https://sandbox-cryptpad.example.com

      # Optional: Log level (silly, verbose, debug, feedback, info, warn, error)
      logLevel: info

    resources:
      limits:
        cpu: 1000m
        memory: 2Gi
      requests:
        cpu: 500m
        memory: 1Gi
