apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: zammad
  namespace: zammad
spec:
  interval: 30m
  dependsOn:
    - name: zammad-postgresql
      namespace: zammad
  chart:
    spec:
      chart: zammad
      version: ">=11.0.0"
      sourceRef:
        kind: HelmRepository
        name: zammad
      interval: 12h
  install:
    timeout: 15m
  upgrade:
    timeout: 15m
  values:
    postgresql:
      enabled: false

    zammadConfig:
      postgresql:
        host: "zammad-db-rw"
        port: 5432
        db: "zammad"
        user: "zammad"
        pass:
          secretName: zammad-db-app
          secretKey: password

    elasticsearch:
      enabled: true
      replicas: 1

    redis:
      enabled: true

    memcached:
      enabled: true

    ingress:
      enabled: true
      className: traefik
      hosts:
        - host: zammad.localhost
          paths:
            - path: /
              pathType: Prefix
