---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: hubble-ui-auth
  namespace: kube-system
spec:
  encryptedData:
    users: AgCFjKkkTEbhegK0k5nuM8+j+3Bez5tp7VtMH3Zy3ftzY0ZquFG7PxBr1sGucDW59OxDzBIxtg4p2ddqpMMI7Ur/tozGhwgjCP07y6S3pIErdtNFTS5T8K5EcOcbnC1lyMlkxAuTDyjQbLcJb3yFK7SQMJIkP3/jC/c3EBE5IUbrmtIiQSTosNIsG0f+PplsKhO9AMOj7u9D+gkrAqVreSgdm1HgcOgLZlQZO2ZL8uqj5Ka++fDeELs5bS372hLAoFsH5qfvN/uOLl1EQDOinwavi6AOUvsS2ubKyGN2HL9o3mW4jI3i2bwCMgS9GBTln/qdFGnrdCNmOFMl9cCrBJ8ngANP2oHPHb5EZQPEJEZ1EztUTLNTvlnnsq4/dshX3ro6HzyM5LNmntMZfLKfszmdLMor4hXiwPKAva6Mkr7AWUWR183Mh+JO/GO5Rb5TO43BhR9aXk4Eu1KDI4nC9Lewbyp3qHCN4T1H1cZk53jO/RQx3GGQKwTSz88LTOfL+lx2Oap9pUYXhDprX9KgGk9A28JKaREhxP3EA1MG1smxN1ftoXzF7Zvq32nyGiMdSxMvl3WmTMpkRfOph/V3F42Svuw381e4raCWgFd9SVpxeFogQhMZvyROUxg6yFYdmqPmut9/Nm/wXwEIE5tkkTf5sHphhlI6d6zGDjaNvZWTypkxdDHC43raaXX+JpAi4KlO8CGd9E/CvS23DBWcqrzItzKxcqTHzE670gDbHFvGqbtZTE9Tm+Gy38PlLCCkPhuxGD005v27dBg/9+E3KV9eXeTkC4HfEA==
  template:
    metadata:
      name: hubble-ui-auth
      namespace: kube-system
