apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: longhorn
  namespace: longhorn-system
spec:
  interval: 30m
  chart:
    spec:
      chart: longhorn
      version: "1.10.1"
      sourceRef:
        kind: HelmRepository
        name: longhorn
      interval: 12h
  install:
    crds: Create
    timeout: 10m
  upgrade:
    crds: CreateReplace
    timeout: 10m
  values:
    defaultSettings:
      defaultReplicaCount: 3
      defaultDataPath: /var/lib/longhorn
      # Allow control plane if needed
      # might want to change to 3 for production cluster..
      # This might be not that useful - running every two days - 
      # since snapshots are currently every 30min, keep 6
      snapshotDataIntegrity: enabled
      snapshotDataIntegrityCronjob: "0 22 * * 2,4,6"
    defaultBackupStore:
      # region after the @ here doesn't matter at all
      backupTarget: s3://longhorn-backups@us-east-1/
      backupTargetCredentialSecret: minio-secret
    longhornManager:
      tolerations:
        - key: node-role.kubernetes.io/control-plane
          operator: Exists
          effect: NoSchedule
    longhornDriver:
      tolerations:
        - key: node-role.kubernetes.io/control-plane
          operator: Exists
          effect: NoSchedule
    longhornUI:
      tolerations:
        - key: node-role.kubernetes.io/control-plane
          operator: Exists
          effect: NoSchedule
