apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: homepage-wordpress
  namespace: homepage-wordpress
spec:
  interval: 30m
  chart:
    spec:
      chart: wordpress
      version: "32.1.1"
      sourceRef:
        kind: HelmRepository
        name: bitnami
      interval: 12h
  install:
    timeout: 10m
  upgrade:
    timeout: 10m
  valuesFrom:
    - kind: Secret
      name: homepage-wordpress-config
      valuesKey: values.yaml
  values:
    resourcesPreset: "none"
    resources:
      requests:
        cpu: 100m
        memory: 256Mi
      limits:
        cpu: 1000m
        memory: 1Gi
    persistence:
      enabled: true
      size: 10Gi
    mysql:
      enabled: true
      auth:
        database: wordpress
        username: wordpress
        existingSecret: homepage-wordpress-mysql
      primary:
        resourcesPreset: "none"
        resources:
          requests:
            cpu: 100m
            memory: 256Mi
          limits:
            cpu: 1000m
            memory: 1Gi
        persistence:
          enabled: true
          size: 2Gi
    ingress:
      enabled: true
      ingressClassName: traefik
      hostname: makerspace.local
      tls: true
      annotations:
        cert-manager.io/cluster-issuer: cluster-ca-issuer
    service:
      type: ClusterIP
