apiVersion: k8s.mariadb.com/v1alpha1
kind: MariaDB
metadata:
  name: mariadb-database
  namespace: homepage-wordpress
spec:
  replicas: 1
  rootPasswordSecretKeyRef:
    name: wordpress-db-credentials
    key: root-password
  username: wordpress
  passwordSecretKeyRef:
    name: wordpress-db-credentials
    key: password
  database: wordpress
  storage:
    size: 8Gi
    storageClassName: longhorn
