---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: vaultwarden-admin-token
  namespace: vaultwarden
spec:
  encryptedData:
    admin-token: AgAywOEam4VGXOocl3GkX+QJT7uL5BRf6Tno8j0XpFfSkP4TpJ9lNBqR8b5ZhzjYPq1QuH8J65Bd7OCDY9pM2Sw3qnACWEynL8NzSrYn3BwejVm3uiafyJ4AOHk7F1PCqksGsUDBXHRMm5t7wKptjAYoxj8DRje1aGhZzf8ps4zEaglRNcHAOO+1hysRwI1sJgrdhYc9Fd5Oiaom3fZVzUV9d/TBpS2gQegDzFyNEavvrWGxsTnQUXId+iUbNzMeekZQY/MSZKck/lS4s6rbfxMV67XnszzKsfB5erzX7RMu1At4wLH3ToIpPTS4y6e19O+AzT/i/7nkE9mHRF/fgO/R1/Js07KfXNxKap+4I1G53+TyOackxXapPj0Bgz8zrwZDAk8kA1hw5qqIUo6Ucw03xlP38JE12Vzar5cbS/dviQmAihY3McDX2Ul+LLFY0QOtRok8+lObqDWkdCO9zvz9zJ1Y6spU9FdGUr8CvAE9CYW44S+zUPmE8DjUrHF74TTb4sNPhmkFu9pEOdRs1TubC16zoCg9+DRjUVQROECk5eQg+mvgfQ9ATJ7nPS2tkFh7P+iYowPME51YHgT4Le9iWX1l390Sa8s0Hxl2CMlkjzpNsuT7JxS8cwAuOLBWlg5QTiS5m7jicshvySolaXz2Mhl7Pt8uaanNv8OKs7ZdCkWgSS+5UUG6q8r907QUhjPLmxZYm8KclkgdQZNOG2mwNfJ6UU00v5iRpIryH0hzcQtJD4Sfr/4wqhx7o0sgw2Sw/IWe/BAC4+hAsQTBArLF
  template:
    metadata:
      name: vaultwarden-admin-token
      namespace: vaultwarden
