---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: vaultwarden-admin-token
  namespace: vaultwarden
spec:
  encryptedData:
    admin-token: AgBkU2VXg/sCToDw4FNkVGK+7Z7D56E+felCkMDrtgxFvIyxXFKEYL7c3zm3a4QLTdlmI4Ztfe597fDAUeMrvTc/OB3FQJET4WZo8XaIFYM+erOMMAVJ9SrY+JLlzULy2dLdjg9pI5guMXqGDiCbgKWBD55q0TPUROnuF6/J+J4UXINhU2Pllr8ooxeu9RcSs4wnM8OnYyIuvPYOLM+SzJz83PAMC3WfCG5JsXs1ARV4X/2CfPS94askJIwlWCVFA+9fXdM97mIE8xeTEJAK6ahXrlOCY3iiITS2zWx6kUKfdRRmZFKm3cXgYGkmPH3psa/SMTZiDBM/hVDSkrC8pnJPLN+x7P4WUVEpS/lyEAC/C5SIcPnd3b2ZRFMMkAjdEIffLIS6Jy50YeMKat6iwNVfAsTT/kE66JwivNwiDLsRjTYcibCXWt7qC7F1HxUwT/E8za/zdNuQkYpN6qmv/rl8hMDiZ9o7ayfsEGIzCbfB+kP9y02sHLVS3YbFfltgyav7f6hQwjBno0sILA4zo9ipdTQ7M9BeHNl1bmvwWNb0HLXLCckEJurDY/Ff6sYUun/ISFy5ysSHWY6vwe3Nt6zYKle74Db8JhqCm1SrLX9LBGgaWvYeEtLe2dC3X5BpwMYOnhpuHlB2c72RDeKDJpZzqa2rYkizdgLIwIUBeXv5KBfanTZ+lWlYY6/V8zrn1qMlg0lyxuRcAjHLFnfBTki8nYN+h2k627vmnrHCfKBfZ8DpDke2DB72xOiOaCKdbAHAp1NvdY08RK/tbmeov14BOvaBUswe89QkCn6wrKnRQ8J1/HJeKcuBw9x6kL/yl3VbGVbdWT5/0RABbOzDcE6gk2oDNWilU/Bo/kwnxlkeI2lryVS8fw==
  template:
    metadata:
      name: vaultwarden-admin-token
      namespace: vaultwarden
