apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: postiz
  namespace: postiz
spec:
  interval: 30m
  chart:
    spec:
      chart: postiz-app
      version: "1.0.5"
      sourceRef:
        kind: HelmRepository
        name: postiz
      interval: 12h
  install:
    timeout: 10m
  upgrade:
    timeout: 10m
  valuesFrom:
    - kind: Secret
      name: postiz-helm-values
      valuesKey: values.yaml
      optional: false
  values:
    postgresql:
      enabled: true
      auth:
        username: postiz
        database: postiz

    redis:
      enabled: true

    env:
      FRONTEND_URL: "http://postiz.localhost:4200"
      NEXT_PUBLIC_BACKEND_URL: "http://postiz.localhost:3000"
      BACKEND_INTERNAL_URL: "http://postiz-postiz-app:3000"
