apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: wikijs-db
  namespace: wikijs
spec:
  instances: 1
  storage:
    size: 1Gi
  bootstrap:
    initdb:
      database: wikijs
      owner: wikijs
