---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: alertmanager-discord-webhook
  namespace: monitoring
spec:
  encryptedData:
    webhook-url: AgC2W56ONZ6nN6AlQwtTn3Lr29UEGOMAQdhE6lirM3CuW92jdU4ofZTGGKlsMObARuCNY/iRwZlqRepViqH2mfDLZKJbX15iGmYMSUw7+SkRaXldGlBNL4ArbBIhaDCQnrwlxZMt+LnXt4RaQKteOmH9po2PhECLQEha9w7VvKudOtGYHtlruPX2YPAjdQyqZQo40he+h0x5wuYUWgcxkVml9w73q0o3RlrHi+rqyaG8JTKYMTxu3xC8VJQEMT8FKASFWarjlcragrTiX/kgYJLyRnZFxpdx3gMrE5nLVXesmGQWGi5hfX6WrFEq0GylB18mUAbz+T/dG+oKHY+ytBkbdQLms0veChpwxQXaZhLmNY6+jVkZHG3tuZ9wPjZ9fEMhTWbYTsdqVRpZ7IK8W6RQ1guubwP+X0EPDWnDCUYfzanmmU+3mX5oNxhiUEyr4mDbanXDWw4CeHwJbPGt9xARVgZrjlnO4JmGIeMMYeSfIlPlGGsHj8Kvxj97j9YeFkVYKsq9JjtYu+7EfHJSdWWSdh98qLvSpT+rgG4+IdQBpo2M6t4QBPw2Krp6QQXjrFf6CSOhRIrWLp2VGSyYBWpkUwYysEZ8P10zq2k8x1e9qIN6wu8wjsrBB6TcLXGehJpRl5+eevUtPQA6kvCY/BvbFpyXtUx8o5hV4UlzJ73MaUkHHlJxpCqEinYn538YTT3SheajUgn82GDI6Yt4yPLSdSi05ryGPRGdhGPNCfz86thag/A4lRxBVJqHFOX7FdQ05SsrtXM+otAtF4iC2x6Td5JOO24O/PL9oh+tfZu9+/HKRMmcheDy78P1Z//G2ameMwmbmXrfMxabU5rkAi9CF33Io7Ee7Tam
  template:
    metadata:
      name: alertmanager-discord-webhook
      namespace: monitoring
