apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: monitoring
resources:
  - ../../../kube-prometheus-stack
  - grafana-sealed-secret.yaml
  - cnpg-podmonitor.yaml
  - alertmanager-discord-sealed-secret.yaml
  - alertmanager-config.yaml
  - etcd-endpoints.yaml
patches:
  - path: helmrelease-patch.yaml
configMapGenerator:
  - name: grafana-dashboard-traefik-17346
    files:
      - dashboards/traefik.json
    options:
      labels:
        grafana_dashboard: "1"
      annotations:
        grafana.com/dashboard-id: "17346"
        grafana.com/dashboard-url: "https://grafana.com/grafana/dashboards/17346"
  - name: grafana-dashboard-cnpg-20417
    files:
      - dashboards/cnpg.json
    options:
      labels:
        grafana_dashboard: "1"
      annotations:
        grafana.com/dashboard-id: "20417"
        grafana.com/dashboard-url: "https://grafana.com/grafana/dashboards/20417"
  - name: grafana-dashboard-ceph-2842
    files:
      - dashboards/ceph.json
    options:
      labels:
        grafana_dashboard: "1"
      annotations:
        grafana.com/dashboard-id: "2842"
        grafana.com/dashboard-url: "https://grafana.com/grafana/dashboards/2842"
