---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: flux-discord-webhook
  namespace: flux-system
spec:
  encryptedData:
    address: AgBhDBapRtPMQSah53K0yGTIDaZLHzC771mymIvufLG0i/6jNwjHSvdd2+xHAMNq3VzIoaquOCMHMIKnLo8TwHHblK0X75LNFP55qqv2hzpWH6A4ua/GkmSZ30NABEn44hKJ6P3QuMB4AxiEsVLrHP7u/1q7YEcqi2bfJCxc/gUOUMnoA2YuDmhUEk7o+99Hx64J4ZIe55MGoCw6amDp8EqI0BGwyw02p6UB8048/wOQy2lJXanG8N0J+q2lJ90eoOzS6KHGQ7faVN/+PtFTPVTgViy11DqA1VKpu7/i7aV6FboI0gRqidHri+1aezUf2meF02OtBHqv8UuiyPIVfpwyv1Hhfk8Rio3J24AfIGR6t6ILiBfKF/xGGHnsFo6Wl1tZGK/nwyjv+uqrwX6LtWlwTxBGTpcyDXKPyNU25fUBujKLBDCgon5/acMIB/03dci3E0xjrJyf+banglaYmUmUELN4TeRDzFLVv983BSnwm2fgJOWMg6bqZ8+6vjqn3W/gTa46JD+gdMCpMVoPNN3C6XEXp2y/RtAkkolV8V9jUfKMVTXw1UL3Do1JX8lLS7wni3hKq3ElmW8ubJQj4o6oUgM/+Z5ULpcfk2JTDZkccJo1Yo3bk0cpZcEESY10v+6JWNnyCEpJ/RMObBoqcU6PMID8KD41k4T/mh/uezpE8AFyPDyLVbK14gywDHA3D+Kp5NEOIoRPFgWPPWTuaiqZYrVf7RbloS9ucEgb2tdgXLg6oxKAyOwLHeJRYP5HuYQCAqnsZAA8rZQGufPJ79uEW0/6AP0/mnO7o44k+RQNls15p2f+3vgY120dGePQIsGhnq9xAdBctv0ZzYZRkLSC1fgeL6AF89JN
  template:
    metadata:
      name: flux-discord-webhook
      namespace: flux-system
