---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: hubble-ui-auth
  namespace: kube-system
spec:
  encryptedData:
    users: AgAtghCqzK/ChhVk/haF0g/mcWF5+xra/tq73erRpVYct0wws0g3PIWYG7kDmQStzsKHtjwxGgiWX18RoTOcQwrscI98VdBRY+v6HCph43CDfQ4SyF/KMDqxEIpbu7yfYGfc/w72p7tWlLMFJqMbpzSdBEj0SRQ8uN2/bXOvuTYHJkdVHG7yNCp8jC14a8Cqq/hub2Pdo18nMjhxHTtl5L++PBMSaSE9Aa7B385OpH+4KOG4vEp7gi5ee5/kpk6o181OCBwOCpqKpWsVPLY1NjNisC6VBwl9bZARFCeX/Lr0yd5BnD7mQhUYAAMxEeOkueMlblZxcWt+haagjaD9MtzBh6hdx4YjqlTqZZ9KqfRyQNVlXmxIK1lj/RQa8inv/m7HtcYnJ6MD4h13XIEA0taGoUgFuubAi732BeEKcGZsZXgn7506S0iqsbmtg3Z0L6L9Ub+EBcTSrS/YXJiLdEIakyu43M1WMxU+Mh5BX5VamzmMzPejA/mx6dhyJHscBBh9kQ1ewAa6LiqBkFmAcE30sT6mwnGSAuUlEG+9Wp520VaamoGyd/YOw83jrieXmqSiqBTykLyDp94XX/EQyZhat0/ZrZBZry4ga3Lt0G1iTHZdvbkZe4bmpPf3WK/pE72H/HKoaBat5o+fkteKzzaIDiH/Ug108dD/xNvnzZ9NubMGicouuSXWSv9h3PjV/cEzJfbXE9ii7McoRylwDQUnKoKNxAdOOmKUEiwhpsfbVeyVMH5wuHggyOZlecRL9wYlE+yZqyPKFCygSQMbBtw+Hok+FMvfjg==
  template:
    metadata:
      name: hubble-ui-auth
      namespace: kube-system
