apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../../networking/cilium
  - hubble-ingress.yaml
  - hubble-ui-sealed-secret.yaml
  - hubble-basicauth-middleware.yaml
