apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: homepage-wordpress
  namespace: homepage-wordpress
spec:
  interval: 30m
  chart:
    spec:
      chart: wordpress
      version: ">=24.0.0"
      sourceRef:
        kind: HelmRepository
        name: bitnami
      interval: 12h
  install:
    timeout: 10m
  upgrade:
    timeout: 10m
  values:
    wordpressUsername: admin
    wordpressPassword: changeme123 # Change this!
    wordpressEmail: admin@makerspace-gt.de
    wordpressBlogName: "Makerspace Gütersloh"

    # Persistence
    persistence:
      enabled: true
      size: 5Gi

    # MySQL
    mysql:
      enabled: true
      auth:
        rootPassword: changeme456 # Change this!
        database: wordpress
        username: wordpress
        password: changeme789 # Change this!
      primary:
        persistence:
          enabled: true
          size: 2Gi

    # Ingress
    ingress:
      enabled: true
      ingressClassName: traefik
      hostname: localhost
      path: /
      pathType: Prefix
