---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: vaultwarden
  namespace: flux-system
spec:
  interval: 5m
  path: ./apps/overlays/local/vaultwarden
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
