---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: vaultwarden
  namespace: flux-system
spec:
  interval: 5m
  path: ./apps/overlays/local/vaultwarden/
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: wikijs
  namespace: flux-system
spec:
  interval: 5m
  dependsOn:
    - name: cloudnative-pg
    - name: traefik
  path: ./apps/overlays/local/wikijs
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
