apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: sealed-secrets
  namespace: flux-system
spec:
  interval: 10m
  path: ./infrastructure/controllers/sealed-secrets
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  wait: true
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: traefik
  namespace: flux-system
spec:
  interval: 10m
  dependsOn:
    - name: sealed-secrets
  path: ./infrastructure/networking/traefik
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  wait: true
