apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: stirling-pdf
  namespace: stirling-pdf
spec:
  interval: 30m
  chart:
    spec:
      chart: stirling-pdf-chart
      version: "2.2.0"
      sourceRef:
        kind: HelmRepository
        name: stirling-pdf
      interval: 12h
  install:
    timeout: 10m
  upgrade:
    timeout: 10m
  values:
    service:
      type: ClusterIP
      port: 8080
