apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: homepage-wordpress
  namespace: homepage-wordpress
spec:
  values:
    ingress:
      enabled: true
      ingressClassName: traefik
      hostname: staging.local
      tls: true
      annotations:
        cert-manager.io/cluster-issuer: staging-ca-issuer
    service:
      type: ClusterIP
    persistence:
      size: 10Gi
