apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - alertmanager-config.yaml
  - cnpg-podmonitor.yaml
  - flux-podmonitor.yaml
  - flux-prometheusrule.yaml
  - csr-prometheusrule.yaml
