apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../../storage/rook-ceph/base
  - ceph-dashboard-ingress.yaml
patches:
  - path: helmrelease-cluster-patch.yaml
    target:
      kind: HelmRelease
      name: rook-ceph-cluster
