name: Validate Manifests

# yamllint disable-line rule:truthy
on:
  pull_request:
    branches: [main]
  push:
    branches: [main]

jobs:
  yaml-lint:
    name: YAML Syntax
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v6
        with:
          python-version: "3.x"

      - name: Install yamllint
        run: pip install yamllint

      - name: Validate YAML syntax
        run: |
          find . '(' -name '*.yaml' -o -name '*.yml' ')' -not -path './talos/*' -not -path '*/flux-system/*' | while read file; do
            echo "Checking $file"
            yamllint "$file" || exit 1
          done

  kubernetes-validation:
    name: Kubernetes Schema
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup kubeconform
        uses: bmuschko/setup-kubeconform@v1

      - name: Validate manifests apps
        run: kubeconform -summary -output pretty -strict -ignore-missing-schemas ./apps
      - name: Validate manifests cluster
        run: kubeconform -summary -output pretty -strict -ignore-missing-schemas ./cluster
      - name: Validate manifests infrastructure
        run: kubeconform -summary -output pretty -strict -ignore-missing-schemas ./infrastructure
      - name: Validate manifests policies
        run: kubeconform -summary -output pretty -strict -ignore-missing-schemas ./policies
      - name: Validate manifests monitoring
        run: kubeconform -summary -output pretty -strict -ignore-missing-schemas -ignore-filename-pattern 'dashboards/.*\.json' ./monitoring
